import { Venue } from '../config/supabase';

export const sampleVenues: Omit<Venue, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    name: 'Grand Palace Hall',
    description: 'Elegant palace-style venue perfect for weddings and corporate events. Features beautiful architecture and modern amenities.',
    address: '123 Palace Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    capacity: 500,
    price_per_hour: 5000,
    price_per_day: 50000,
    rating: 4.5,
    image_url: 'https://via.placeholder.com/400x300/4A90E2/FFFFFF?text=Grand+Palace',
    amenities: ['Parking', 'Catering', 'Audio/Visual', 'Air Conditioning', 'Wi-Fi', 'Decoration'],
    is_available: true,
  },
  {
    name: 'Modern Conference Center',
    description: 'State-of-the-art conference facility with modern amenities, perfect for business meetings and corporate events.',
    address: '456 Business Park',
    city: 'Delhi',
    state: 'NCR',
    capacity: 200,
    price_per_hour: 2500,
    price_per_day: 25000,
    rating: 4.2,
    image_url: 'https://via.placeholder.com/400x300/50C878/FFFFFF?text=Conference+Center',
    amenities: ['Projector', 'Sound System', 'Video Conferencing', 'Catering', 'Wi-Fi', 'Parking'],
    is_available: true,
  },
  {
    name: 'Garden Wedding Venue',
    description: 'Beautiful outdoor garden venue surrounded by nature, perfect for romantic weddings and outdoor celebrations.',
    address: '789 Garden Lane',
    city: 'Bangalore',
    state: 'Karnataka',
    capacity: 300,
    price_per_hour: 3500,
    price_per_day: 35000,
    rating: 4.7,
    image_url: 'https://via.placeholder.com/400x300/FF6B6B/FFFFFF?text=Garden+Venue',
    amenities: ['Outdoor Setup', 'Garden Decoration', 'Catering', 'Photography Area', 'Parking', 'Restrooms'],
    is_available: true,
  },
  {
    name: 'Luxury Banquet Hall',
    description: 'Premium banquet hall with luxury amenities and catering services, ideal for high-end events and celebrations.',
    address: '321 Luxury Street',
    city: 'Chennai',
    state: 'Tamil Nadu',
    capacity: 400,
    price_per_hour: 4500,
    price_per_day: 45000,
    rating: 4.3,
    image_url: 'https://via.placeholder.com/400x300/9B59B6/FFFFFF?text=Luxury+Banquet',
    amenities: ['Luxury Decor', 'Premium Catering', 'Audio/Visual', 'Air Conditioning', 'Wi-Fi', 'Valet Parking'],
    is_available: true,
  },
  {
    name: 'Riverside Event Center',
    description: 'Stunning riverside location with panoramic views, perfect for memorable events and celebrations.',
    address: '654 River View Road',
    city: 'Hyderabad',
    state: 'Telangana',
    capacity: 250,
    price_per_hour: 4000,
    price_per_day: 40000,
    rating: 4.6,
    image_url: 'https://via.placeholder.com/400x300/3498DB/FFFFFF?text=Riverside+Center',
    amenities: ['Riverside View', 'Outdoor Seating', 'Catering', 'Photography Spots', 'Parking', 'Boat Access'],
    is_available: true,
  },
  {
    name: 'Tech Hub Meeting Space',
    description: 'Modern tech-focused meeting space with cutting-edge technology, perfect for startups and tech events.',
    address: '987 Innovation Drive',
    city: 'Pune',
    state: 'Maharashtra',
    capacity: 150,
    price_per_hour: 3000,
    price_per_day: 30000,
    rating: 4.4,
    image_url: 'https://via.placeholder.com/400x300/E74C3C/FFFFFF?text=Tech+Hub',
    amenities: ['High-Speed Internet', 'Video Conferencing', 'Whiteboards', 'Coffee Bar', 'Parking', 'Meeting Rooms'],
    is_available: true,
  },
];

// Function to insert sample venues (run this in Supabase SQL editor)
export const insertSampleVenuesSQL = `
INSERT INTO venues (name, description, address, city, state, capacity, price_per_hour, price_per_day, rating, image_url, amenities, is_available)
VALUES 
  ('Grand Palace Hall', 'Elegant palace-style venue perfect for weddings and corporate events. Features beautiful architecture and modern amenities.', '123 Palace Road', 'Mumbai', 'Maharashtra', 500, 5000, 50000, 4.5, 'https://via.placeholder.com/400x300/4A90E2/FFFFFF?text=Grand+Palace', ARRAY['Parking', 'Catering', 'Audio/Visual', 'Air Conditioning', 'Wi-Fi', 'Decoration'], true),
  ('Modern Conference Center', 'State-of-the-art conference facility with modern amenities, perfect for business meetings and corporate events.', '456 Business Park', 'Delhi', 'NCR', 200, 2500, 25000, 4.2, 'https://via.placeholder.com/400x300/50C878/FFFFFF?text=Conference+Center', ARRAY['Projector', 'Sound System', 'Video Conferencing', 'Catering', 'Wi-Fi', 'Parking'], true),
  ('Garden Wedding Venue', 'Beautiful outdoor garden venue surrounded by nature, perfect for romantic weddings and outdoor celebrations.', '789 Garden Lane', 'Bangalore', 'Karnataka', 300, 3500, 35000, 4.7, 'https://via.placeholder.com/400x300/FF6B6B/FFFFFF?text=Garden+Venue', ARRAY['Outdoor Setup', 'Garden Decoration', 'Catering', 'Photography Area', 'Parking', 'Restrooms'], true),
  ('Luxury Banquet Hall', 'Premium banquet hall with luxury amenities and catering services, ideal for high-end events and celebrations.', '321 Luxury Street', 'Chennai', 'Tamil Nadu', 400, 4500, 45000, 4.3, 'https://via.placeholder.com/400x300/9B59B6/FFFFFF?text=Luxury+Banquet', ARRAY['Luxury Decor', 'Premium Catering', 'Audio/Visual', 'Air Conditioning', 'Wi-Fi', 'Valet Parking'], true),
  ('Riverside Event Center', 'Stunning riverside location with panoramic views, perfect for memorable events and celebrations.', '654 River View Road', 'Hyderabad', 'Telangana', 250, 4000, 40000, 4.6, 'https://via.placeholder.com/400x300/3498DB/FFFFFF?text=Riverside+Center', ARRAY['Riverside View', 'Outdoor Seating', 'Catering', 'Photography Spots', 'Parking', 'Boat Access'], true),
  ('Tech Hub Meeting Space', 'Modern tech-focused meeting space with cutting-edge technology, perfect for startups and tech events.', '987 Innovation Drive', 'Pune', 'Maharashtra', 150, 3000, 30000, 4.4, 'https://via.placeholder.com/400x300/E74C3C/FFFFFF?text=Tech+Hub', ARRAY['High-Speed Internet', 'Video Conferencing', 'Whiteboards', 'Coffee Bar', 'Parking', 'Meeting Rooms'], true);
`; 